### ISSUE TITLE
ManiaDrive

### ISSUE THREAD

**Issue by neuromancer** [piranha/osgameclones#310]
```
- name: TrackMania
  clones:
    - name: ManiaDrive
      url: http://maniadrive.raydium.org/
```
