### ISSUE TITLE
Daggerfall Unity

### ISSUE THREAD

**Issue by neuromancer** [piranha/osgameclones#312]
```
- name: Daggerfall II
  clones:
    - name: Daggerfall Unity
      url: http://www.dfworkshop.net/
      repo: https://github.com/Interkarma/daggerfall-unity
```
