### ISSUE TITLE
OpenRW (GTA III reimplementation)

### ISSUE THREAD

**Issue by neuromancer** [piranha/osgameclones#315]
```
- name: Grand Theft Auto III
  reimplementation:
    - name: OpenReWrite
      repo: https://github.com/danhedron/openrw
```
