### ISSUE TITLE
Librelancer

### ISSUE THREAD

**Issue by neuromancer** [piranha/osgameclones#322]
```
- name: Freelancer
  reimplementations:
    - name: Librelancer
      url: https://github.com/CallumDev/Librelancer
      repo: https://github.com/CallumDev/Librelancer
```
