### ISSUE TITLE
Visual Pinball?

### ISSUE THREAD

**Issue by neuromancer** [piranha/osgameclones#346]
Please review if this open sourced game is suitable to include.

```
- name: Visual Pinball
  clones:
    - name: Visual Pinball
      repo: https://svn.code.sf.net/p/vpinball/code/

```
