### ISSUE TITLE
Game meta key

### ISSUE THREAD

**Issue by nikuda** [piranha/osgameclones#360]
To be able to support 'genre' and similar meta information schema needs to change to hold genres at the name level, as you don't want to re-tag every clone/reimplementation.

```yaml
# Before
- name: Dune
  clones:
    - name: OpenDune
      genre: Real-Time Strategy
    - name: Dune Legacy
      genre: Real-Time Strategy
  reimplementations: ...

# After
- game:
    name: Dune
    genre: Real-Time Strategy
    theme: Sci-Fi
  clones: ...
  reimplementations: ...
```

**Comment by nikuda** [comment]
Simpler solution implemented in https://github.com/piranha/osgameclones/pull/358#issuecomment-252410556

```yaml
- name: Dune
  meta:
    genre: 
      - Real-Time Strategy
    theme: 
      - Sci-Fi
  clones: ...
  reimplementations: ...
```
