### ISSUE TITLE
Populate genre, subgenre & theme meta for all games

### ISSUE THREAD

**Issue by nikuda** [piranha/osgameclones#366]
Volunteers needed.

It mostly involves going to www.giantbomb.com/games, searching for the game and then noting down the genre and theme entries from the info box on the right side.

<img width="347" alt="screen shot 2016-10-10 at 11 12 08 am" src="https://cloud.githubusercontent.com/assets/723683/19224883/6fd8387e-8eda-11e6-9318-21ce20585ff8.png">

If GiantBomb doesn't have a record of the game then use a combination of wikipedia game description and pick a fitting genre from:
- https://en.wikipedia.org/wiki/List_of_video_game_genres

See `schema.yaml` file for list of genres, subgenres and themes. The list of genres should stay more or less the same, the list of subgenres is the one that should be expanded if need be.

The meta format looks like this:

``` yaml
- name: Game name
  meta:
    genre: [Role-Playing]
    subgenre: [Roguelike]
    theme: [Sci-Fi, Horror]
  clones: ...
  ...
```
