### ISSUE TITLE
Content key for clones/remakes

### ISSUE THREAD

**Issue by nikuda** [piranha/osgameclones#373]
New key in the clone/remake schema to indicate whether the game data is available

```yaml
name: freegish
repo: https://github.com/freegish/freegish
content: open
```

What could the acceptable values be? Maybe something like:

```yaml
content: commercial | free | open
```
