### ISSUE TITLE
Media schema changes

### ISSUE THREAD

**Issue by nikuda** [piranha/osgameclones#374]
Seems a lot of people struggle with the media data, there are a lot of links where the thumbnail is the large image, and the link points to the thumbnail. We should simplify it by removing the ability to assign urls and not have thumbnails, and then move all image links in one array under `images`. In the end `media` data would go from this:

```yaml
name: game name
media:
  - image: link
    url: link
  - image: link
    url: link
  - image: link
    url: link
  - image: link
    url: link
  - youtube: video id
```

to this:

```yaml
name: game name
media:
  images:
    - link
    - link
    - link
  youtube: video id
```

**Comment by nikuda** [comment]
Changed to this

```yaml
name: game name
images:
  - link
  - link
  - link
video:
  youtube: video id
  vimeo: video id
```
