### ISSUE TITLE
Magic The Gathering: Online clones

### ISSUE THREAD

**Issue by fanna** [piranha/osgameclones#410]
Magic The Gathering: Online

```yaml
- name: [Magic The Gathering: Online, Magic: The Gathering Online]
  names: [Magic The Gathering: Online, Magic: The Gathering Online]
    -
  meta:
    genre: [Strategy, Simulation, Puzzle]
    subgenre: [Card Game, Turn-Based Tactics]
    theme: [Fantasy]
  clones:
    - name: Forge
      repo: http://svn.slightlymagic.net/websvn/listing.php?repname=forge
      url: http://www.slightlymagic.net/wiki/Forge
      development: very active
      status: playable
      lang: [Java]
   - name: XMage
      repo: https://github.com/magefree/mage
      url: http://xmage.de/
      development: very active
      status: playable
      lang: [Java]
   - name: Magarena
      repo: https://github.com/magarena/magarena
      url: https://magarena.github.io/
      development: very active
      status: playable
      lang: [Java]
```
