### ISSUE TITLE
What engine does the game play?

### ISSUE THREAD

**Issue by medeirosarthur031** [piranha/osgameclones#434]
New game

```yaml
- name:
  names:
    -
  meta:
    genre: []
    subgenre: []
    theme: []
  remakes:
    - name:
      repo:
      url:
      development:
      status:
      lang: []
      framework: []
      license:
      content:
      info:
      updated:
      images:
        -
      video:
        youtube:
        vimeo:
```
