### ISSUE TITLE
Snipes

### ISSUE THREAD

**Issue by AlexFolland** [piranha/osgameclones#435]
I'm not sure if I've formatted this properly, and the license is not specified anywhere that I can tell, but the engine author (David Ellsworth aka Deadcode) got permission from the original developer of the game (Drew Major) to release this port.  Please check my work here with the formatting and choices for the fields.  A lot more information can be found in the release announcement thread for anything uncertain.  https://www.vogons.org/viewtopic.php?f=7&t=49073

```yaml
name: [Snipes, Snipes (video game)]
repo: https://github.com/Davidebyzero/Snipes
url: https://www.vogons.org/viewtopic.php?f=7&t=49073
development: complete
status: playable
lang: [C++]
framework: [SDL2]
license: Custom
content: free
info: reverse-engineered from original binary, aims for 100% logic compatibility with original game
updated: 2016-08-04
```
