### ISSUE TITLE
Add OpenRW

### ISSUE THREAD

**Issue by undrskr** [piranha/osgameclones#442]
OpenRW

```yaml
- name: Grand Theft Auto III
  names:
    -
  meta:
    genre: [action]
    subgenre: [TPS]
    theme: [criminal]
  remakes:
    - name: OpenRW
      repo: https://github.com/rwengine/openrw
      url: http://openrw.org/
      development: Sporadic
      status: Unplayable
      lang: [English]
      framework: [SDL]
      license: GPLv3
      content:
      info:
      updated:
      images:
        -
      video:
        youtube:
        vimeo:
```
