### ISSUE TITLE
Project Dollhouse

### ISSUE THREAD

**Issue by Afr0** [piranha/osgameclones#445]
New game

```yaml
- name: The Sims Online
  names:
    -
  meta:
    genre: [MMO]
    subgenre: [Simulation]
    theme: [life]
  remakes:
    - name: Project Dollhouse
      repo: https://github.com/Afr0Games/Project-Dollhouse
      url: http://www.afr0games.com
      development:
      status: active
      lang: [C#]
      framework: [Monogame]
      license: Mozilla
      content:
      info:
      updated:
      images:
        -
      video:
        youtube:
        vimeo:
```
