### ISSUE TITLE
Missing FreeCol

### ISSUE THREAD

**Issue by michaelmberger** [piranha/osgameclones#478]
New game

```yaml
- name:Colonization
  names:Sid Meier's Colonization
    -
  meta:
    genre: [Turn Based Strategy]
    subgenre: [World Builder]
    theme: [Civilization]
  remakes:
    - name:FreeCol
      repo:https://git.code.sf.net/p/freecol/git freecol-git
      url:http://www.freecol.org/
      development:
      status:Active
      lang: [Multi]
      framework: []
      license:GPLv2
      content:
      info:
      updated:
      images:
        -
      video:
        youtube:
        vimeo:
```
