### ISSUE TITLE
Missing FreeCiv

### ISSUE THREAD

**Issue by miniwark** [piranha/osgameclones#481]
New game

```yaml
- name:Civilization
  names:Sid Meier's Civilization
    -
  meta:
    genre: [Turn Based Strategy]
    subgenre: [World Builder]
    theme: [Civilization]
  remakes:
    - name:FreeCiv
      repo:https://github.com/freeciv/
      url:http://www.freeciv.org/
      development:
      status:Active
      lang: [Multi]
      framework: []
      license:GPLv2
      content:
      info:
      updated:
      images:
        -
      video:
        youtube:
        vimeo:
```
