### ISSUE TITLE
Open Terraria Rewrite not available

### ISSUE THREAD

**Issue by HQupgradeHQ** [piranha/osgameclones#485]
```yaml
- name:
  names:
    -
  meta:
    genre: []
    subgenre: []
    theme: []
  remakes:
    - name:
      repo:
      url: https://web.archive.org/web/20160224050506/https://github.com/Shockah/Open-Terraria-Rewrite
      development:
      status: github repo not available 
  
```
