### ISSUE TITLE
Addition: Megalomania

### ISSUE THREAD

**Issue by dlasher** [piranha/osgameclones#491]
New game

```yaml
- name: Megalomania
  names:
    -
  meta:
    genre: [RTS]
    subgenre: []
    theme: []
  remakes:
    - name: Gigalomania
      repo: Sourceforge
      url: http://gigalomania.sourceforge.net/
      development:
      status: available for Windows, Linux, Mac OS X, Android, AROS, MorphOS, AmigaOS 4, and Nokia Symbian.
      lang: []
      framework: []
      license:
      content:
      info:
      updated:
      images:
        -
      video:
        original youtube: https://www.youtube.com/watch?v=jBVDbTT0kzU
        remake youtube: https://www.youtube.com/watch?v=lTtT9p9DVL8
        vimeo:
```
