### ISSUE TITLE
Multiplayer type

### ISSUE THREAD

**Issue by nikuda** [piranha/osgameclones#522]
Proposing a new key called `mulitplayer` that should hold information about what modes of mulitplayer support a particular game has. i.e. 'split-screen'? It might be too hard to categorise this, but want to see what you guys think.

```
repo: github.com/some/game
lang: [C, Pythong]
mutliplayer: 
  - mode: split-screen
    players: 4
  - mode: tcp/ip
    players: 12
```
