### ISSUE TITLE
Jazz 2 Resurrection

### ISSUE THREAD

**Issue by Darknior** [piranha/osgameclones#530]
New game

```yaml
- name: Jazz 2 Resurrection
  remakes: [Jazz Jackrabbit 2]
  clones: [Jazz Jackrabbit 2]
  repo: https://github.com/deathkiller/jazz2
  url: https://www.jazz2online.com/jcf/showthread.php?t=20089
  feed:
  development: active
  status: playable
  multiplayer: [Online, LAN to come]
  lang: [English]
  framework: [mono, c#]
  license:
  content: open
  info: For the moment only use OpenGL ES 3
  updated: Oct 25, 2017 (0.4.8)
  images: https://drive.google.com/drive/folders/0B8bpor58RNwHekRBQjhPdXg1Z1k
    -
  video:
    youtube: https://www.youtube.com/watch?v=6ZHq8LlXOag&feature=youtu.be
    vimeo:
```
