### ISSUE TITLE
Minetest clone of Minecraft

### ISSUE THREAD

**Issue by jonadem** [piranha/osgameclones#535]
New game

```yaml
- name: Minetest
  remakes: []
  clones: [Minecraft]
  repo: https://github.com/minetest/minetest
  url: https://www.minetest.net/
  feed:
  development:
  status:
  multiplayer: []
  lang: [C++]
  framework: []
  license: CC BY-SA 3.0
  content:
  info:
  updated:
  images:
    -
  video:
    youtube:
    vimeo:
```
